version: "3"

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      -  MYSQL_ROOT_PASSWORD=password
      -  MYSQL_USER=test
      -  MYSQL_PASSWORD=test
    ports:
      - '3306:3306'
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
    restart: always
